/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JS": {
      "key": "JS",
      "scope": "tags",
      "path": "/tag/JS/",
      "pageKeys": [
        "v-40628037",
        "v-7ae50b77",
        "v-73957bd7",
        "v-b6aa8092",
        "v-4a4e9b97",
        "v-10814812",
        "v-1cd4fc97",
        "v-d0c51152",
        "v-11e17f77",
        "v-25688852",
        "v-0b989bb7"
      ]
    },
    "HTML": {
      "key": "HTML",
      "scope": "tags",
      "path": "/tag/HTML/",
      "pageKeys": [
        "v-19b76f57"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "tags",
      "path": "/tag/正则/",
      "pageKeys": [
        "v-7cf8a037"
      ]
    }
  },
  "categories": {
    "前端小笔记": {
      "key": "前端小笔记",
      "scope": "categories",
      "path": "/categories/前端小笔记/",
      "pageKeys": [
        "v-40628037",
        "v-19b76f57",
        "v-7ae50b77",
        "v-73957bd7",
        "v-b6aa8092",
        "v-4a4e9b97",
        "v-10814812",
        "v-1cd4fc97",
        "v-d0c51152",
        "v-0b989bb7"
      ]
    },
    "排序": {
      "key": "排序",
      "scope": "categories",
      "path": "/categories/排序/",
      "pageKeys": [
        "v-11e17f77"
      ]
    },
    "Promise": {
      "key": "Promise",
      "scope": "categories",
      "path": "/categories/Promise/",
      "pageKeys": [
        "v-25688852"
      ]
    },
    "正则": {
      "key": "正则",
      "scope": "categories",
      "path": "/categories/正则/",
      "pageKeys": [
        "v-7cf8a037"
      ]
    }
  },
  "timeline": {}
}